name: Arduino Library CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=$HOME/bin sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Install Arduino CLI specific version
        run: |
          arduino-cli update
          arduino-cli version

      - name: Run arduino-lint
        run: |
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "PubSubClient"
          arduino-cli lib list
